### ISSUE TITLE
Clarification for periods < 1

### ISSUE THREAD

**Issue by timmb** [stegu/psrdnoise#12]
Is there a reason the `p` parameter is a `vec3` instead of an `ivec3`.

I'm trying to work out if there's any prospect of having a non-integer period. The intro comment mentions "any integer period", and it makes sense that the period needs to be a multiple of the dimension of the underlying simplex shape.

In my experiments, non-integer periods seem to be cyclic to some period.

Thanks,
Tim

**Comment by stegu** [comment]
There is no reason to specify anything but integer values for p, and
anything else will yield weird results. However, the code is deliberately
designed not to require integer types. Operations on integers are still
quite a lot slower than floats on many GLSL platforms. Also, the modulo
operation to wrap to the period is performed on float coordinates, and it's
not even marginally speeded up by using an integer type for p. If anything,
it slows down the code because a conversion is required.

The code was written for speed, and I tested it on many different
platforms. Low end GPUs and mobile GPUs are still very different animals
compared to the high performance gaming chips, and my "old school" code
seems to run better on low end hardware, and perform no worse on the high
end.

**Comment by timmb** [comment]
Makes sense - thank you
